# .readthedocs.yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with doc

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true