name: Tests

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}

      - name: Cache Packages
        id: package-cache
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies using Poetry
        if: steps.package-cache.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Lints
        run: |
          poetry run pylint web3cat
      - name: Test with pytest
        run: |
          poetry run pytest