name: Tests

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies using Poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Lints
        run: |
          poetry run pylint web3cat
      - name: Test with pytest
        run: |
          poetry run pytest